[package]
name = "pciids"
version = "0.1.0"
authors = ["Wren Turkal <wt@penguintechs.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
indoc = "0.3"
log = "0.4"
paw = "1.0"
pest = "2.0"
pest_derive = "2.0"
rand = "0.3"
structopt = { version = "0.3", features = [ "paw" ] }
